gText_Birch_Welcome::
	.string "Hey, champ!\p"
	.string "Today is the first day of your \n"
	.string "new life as a gym leader!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "The POKéMON League is trying a\n"
	.string "new type of gym, and your dad\l"
	.string "thought you should take over.\p"
	.string "You're going to have to think\n"
	.string "about what type your gym will be\l"
	.string "and how to take on challengers.\p"
	.string "I'm going to need an updated\n"
	.string "picture for you, though...\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Which of these is it?$"

gText_Birch_BoyOrGirl::
	.string "This one?\n"
	.string "Or this one?$"

gText_Birch_WhatsYourName::
	.string "All right. As a gym leader,\n"
	.string "do you want to go by any nickname?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "There we go!\p"
	.string "Gym leader {PLAYER}{KUN} of\n"
	.string "PETALBURG gym.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Let's get to PETALBURG!\p"
	.string "$"
